Enterprises.CMS.Web/Areas/Admin/Controllers/NewsTypeController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp.Web.Mvc.Authorization;
using Abp.Web.Mvc.Extensions;
using Enterprises.CMS.NewsType;
using Enterprises.CMS.NewsType.Dto;



namespace Enterprises.CMS.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 菜单类型
    /// </summary>
    [AbpMvcAuthorize]
    public class NewsTypeController :  CmsAdminControllerBase
    {
        private readonly INewsTypeAppService _newsTypeAppService;
        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="fNewsTypeAppService"></param>
        public NewsTypeController(INewsTypeAppService fNewsTypeAppService)
        {
            _newsTypeAppService = fNewsTypeAppService;
        }


        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        //[AbpMvcAuthorize("Administration.NewsType")]
        public ActionResult Index(int id = 1)
        {
            var model = new NewsTypeSearchInput();
            model.PageIndex = id;
            return View(model);
        }

        //[AbpMvcAuthorize("Administration.NewsType")]
        [HttpGet]
        public async Task<ActionResult> List(int id = 1)
        {
            var list = await _newsTypeAppService.List(new NewsTypeSearchInput(), id);
            return PartialView("_PageTable", list);
        }

        //[AbpMvcAuthorize("Administration.NewsType")]
        [HttpPost]
        public async Task<ActionResult> List(NewsTypeSearchInput searchModel, int id = 1)
        {
            var list = await _newsTypeAppService.List(searchModel, id);
            return PartialView("_PageTable", list);
        }

        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        //[AbpMvcAuthorize("Administration.NewsType")]
        public PartialViewResult Create()
        {
            var model = new NewsTypeCreateInput();
            return PartialView(model);

        }

        /// <summary>
        /// 用户列表
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        //[AbpMvcAuthorize("Administration.NewsType")]
        public async Task<JsonResult> Create(NewsTypeCreateInput model)
        {
            if (ModelState.IsValid)
            {
                await _newsTypeAppService.Create(model);
                return Json(new { result = true, errors = "" });
            }

            return Json(new { result = false, errors = ModelState.AllModelStateErrors() });
        }

        //[AbpMvcAuthorize("Administration.NewsType")]
        public async Task<ActionResult> Edit(int id)
        {
            var model =await _newsTypeAppService.GetSingle(id);
            return PartialView(model);
        }

        [HttpPost]
        //[AbpMvcAuthorize("Administration.NewsType")]
        public async Task<JsonResult> Edit(NewsTypeCreateInput model)
        {
            if (ModelState.IsValid)
            {
                await _newsTypeAppService.Edit(model);
                return Json(new { result = true, errors = "" });
            }

            return Json(new { result = false, errors = ModelState.AllModelStateErrors() });
        }

        [HttpGet]
        //[AbpMvcAuthorize("Administration.NewsType")]
        public async Task<ActionResult> Delete(int id)
        {
            await _newsTypeAppService.Delete(id);
            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        }

    }
}

Enterprises.CMS.Web/Areas/Admin/Views/NewsType/Create.cshtml
@model Enterprises.CMS.NewsType.Dto.NewsTypeCreateInput

<div class="modal-header">
    <button data-dismiss="modal" class="close" type="button">×</button>
    <h3>新增记录</h3>
</div>
<div class="modal-body">
    @using (Html.BeginForm("Create", "NewsType", FormMethod.Post, new { @class= "form-horizontal",id= "saveForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="control-group">
            <label class="control-label">新闻类型 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.TypeName, new {@class = "span3", placeholder = "新闻类型"})
                <span class="help-inline">@Html.ValidationMessageFor(p => p.TypeName)</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">新闻编号 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.TypeCode, new {@class = "span3", placeholder = "新闻编号"})
                <span class="help-inline">@Html.ValidationMessageFor(p => p.TypeCode)</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">在菜单显示 :</label>
            <div class="controls">
                <div data-toggle="buttons-radio" class="btn-group form-inline">
                    <label><input type="radio" style="margin-bottom: 5px;" name="ShowMenu" value="True" checked="checked" />是 &nbsp;</label>
                    <label><input type="radio" style="margin-bottom: 5px;" name="ShowMenu" value="False" />否 &nbsp;</label>
                </div>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">排序顺序 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.SortOrder, new { @class = "span3", placeholder = "排序顺序" })
                <span class="help-inline">@Html.ValidationMessageFor(p => p.SortOrder)</span>
            </div>
        </div>

    }
</div>
<div class="modal-footer">
    <a id="btSave" class="btn btn-primary" href="#">确定</a>
    <a data-dismiss="modal" class="btn btn-inverse" href="#">取消</a>
</div>

Enterprises.CMS.Web/Areas/Admin/Views/NewsType/Edit.cshtml
@model Enterprises.CMS.NewsType.Dto.NewsTypeCreateInput

<div class="modal-header">
    <button data-dismiss="modal" class="close" type="button">×</button>
    <h3>修改记录</h3>
</div>
<div class="modal-body">
    @using (Html.BeginForm("Edit", "NewsType", FormMethod.Post, new { @class = "form-horizontal", id = "saveForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(p=>p.Id)
         <div class="control-group">
            <label class="control-label">新闻类型 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.TypeName, new {@class = "span3", placeholder = "新闻类型"})
                <span class="help-inline">@Html.ValidationMessageFor(p => p.TypeName)</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">新闻编号 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.TypeCode, new {@class = "span3", placeholder = "新闻编号"})
                <span class="help-inline">@Html.ValidationMessageFor(p => p.TypeCode)</span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">在菜单显示 :</label>
            <div class="controls">
                <div data-toggle="buttons-radio" class="btn-group form-inline">
                    <label><input type="radio" name="ShowMenu" style="margin-bottom: 5px;" value="True" @string.Format("{0}", @Model.ShowMenu ? "checked=\"checked\"" : "")/>是 &nbsp;</label>
                    <label><input type="radio" name="ShowMenu" style="margin-bottom: 5px;" value="False" @string.Format("{0}", @Model.ShowMenu == false ? "checked=\"checked\"" : "")/>否 &nbsp;</label>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">排序顺序 :</label>
            <div class="controls">
                @Html.TextBoxFor(p => p.SortOrder, new {@class = "span3", placeholder = "排序顺序"})
                <span class="help-inline">@Html.ValidationMessageFor(p => p.SortOrder)</span>
            </div>
        </div>
    }
</div>
<div class="modal-footer">
    <a id="btSave" class="btn btn-primary" href="#">确定</a>
    <a data-dismiss="modal" class="btn btn-inverse" href="#">取消</a>
</div>

Enterprises.CMS.Web/Areas/Admin/Views/NewsType/Index.cshtml
@using Enterprises.CMS.Authorization
@using Webdiyer.WebControls.Mvc
@model Enterprises.CMS.NewsType.Dto.NewsTypeSearchInput
@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.ActiveMenu = "新闻类型";
}

<div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> 首页</a> <a href="#" class="current">新闻类型</a> </div>
    <h1>新闻类型</h1>
</div>
<div class="container-fluid">
    <hr>
    @using (Ajax.BeginForm("List", new RouteValueDictionary { { "id", "" } }, new AjaxOptions { UpdateTargetId = "AjaxPagerPangel", InsertionMode = InsertionMode.Replace }, new RouteValueDictionary { { "id", "searchForm" } }))
    {
        <div class="container-fluid" style="margin-bottom: 20px;">
            <div class="row-fluid">
                <div class="span3 form-inline">
                    <label>新闻类型：</label>
                    @Html.TextBoxFor(p => p.TypeName, new { @class = "form-control", placeholder = "新闻类型" })
                </div>
                <div class="span3 form-inline">
                    <label>在菜单显示：</label>
                    <div data-toggle="buttons-radio" class="btn-group">
                        <label><input type="radio" style="margin-bottom: 5px;" name="ShowMenu" value="True" />是 &nbsp;</label>
                        <label><input type="radio" style="margin-bottom: 5px;" name="ShowMenu" value="False" />否 &nbsp;</label>
                    </div>
                </div>

                <div class="span3">
                    <button type="submit" accesskey="S" class="btn btn-info">查询</button>
                </div>
            </div>
        </div>
    }

    @if (IsGranted(PermissionNames.AdministrationUsersCreate))
    {
        <a id="btCreate" href="javascript:void(0);" url="~/admin/NewsType/create" class="btn btn-success">新增</a>
    }
    <div class="row-fluid" id="AjaxPagerPangel">
        @{ Html.RenderAction("list", "NewsType", new { id = Model.PageIndex }); }
    </div>
</div>
<div id="pageModal" class="modal hide"></div>
@section Scripts{
    <script src="~/Scripts/form.js"></script>
    @{Html.RegisterMvcPagerScriptResource();}
}

Enterprises.CMS.Web/Areas/Admin/Views/NewsType/_PageTable.cshtml
@using Webdiyer.WebControls.Mvc
@model Webdiyer.WebControls.Mvc.PagedList<Enterprises.CMS.NewsType.Dto.NewsTypeListDto>

<div class="span12">
    <div class="widget-box">
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th style="width: 20%">新闻类型</th>
                    <th style="width: 20%">新闻编号</th>
                    <th style="width: 20%">在菜单显示</th>
                    <th style="width: 20%">排序顺序</th>
                    <th style="width: 10%">操作</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr class="gradeX">
                        <td>@item.TypeName</td>
                        <td>@item.TypeCode</td>
                        <td>@item.ShowMenu</td>
                        <td>@item.SortOrder</td>
                        <td style="text-align: center">
                            <a href="javascript:void(0);" url="@Href("~/admin/NewsType/edit/")@item.Id" class="btn btn-primary btn-mini editflag">修改</a>
                            <a href="javascript:void(0);" url="~/admin/NewsType/Delete/@item.Id" class="btn btn-danger btn-mini deleteflag">删除</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div id="badoopager" class="span12" style="margin: 0; padding: 0;color: #666">
    <div style="float:left; ">当前显示第 @Model.CurrentPageIndex 页，共 @Model.TotalPageCount 页 @Model.TotalItemCount 条记录</div>
    @Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "id", CurrentPagerItemTemplate = "<span class=\"current\">{0}</span>", DisabledPagerItemTemplate = "<span class=\"disabled\">{0}</span>", Id = "pager" }, new MvcAjaxOptions { UpdateTargetId = "AjaxPagerPangel", HttpMethod = "Post", DataFormId = "searchForm" })
</div>